# SUBMISSION MAKER JUST FEATURES

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import metrics

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [4]:
pwd

'N:\\Documents\\General-Assembly\\dsi-cc13\\projects\\project_2\\deliverables\\code'

In [9]:
# Import CSV
train =  pd.read_csv('../data/clean-train-engineered.csv')
test = pd.read_csv('../data/clean-test-engineered.csv')

# FEATURES1

In [10]:
# Features
features1 = ['ms_subclass',

  'neighborhood',
  'bldg_type',
  'house_style',
  'overall_cond',
  'year_built',

  'heating_qc',
  'central_air',
  'electrical',
  'full_bath',
  'half_bath',
  'bedroom_abvgr',
  'kitchen_qual',
  'totrms_abvgrd',
  'functional',
  'fireplaces',
  'garage_cars',
  'garage_qual',
  'garage_cond',
  'mo_sold',
  'yr_sold',
  'sale_type']
features1

['ms_subclass',
 'neighborhood',
 'bldg_type',
 'house_style',
 'overall_cond',
 'year_built',
 'heating_qc',
 'central_air',
 'electrical',
 'full_bath',
 'half_bath',
 'bedroom_abvgr',
 'kitchen_qual',
 'totrms_abvgrd',
 'functional',
 'fireplaces',
 'garage_cars',
 'garage_qual',
 'garage_cond',
 'mo_sold',
 'yr_sold',
 'sale_type']

In [11]:
dummy_columns1 = [
                'neighborhood',
                'bldg_type',
                'house_style',

                'heating_qc',
                'central_air',
                'electrical',
                'kitchen_qual',
                'functional',
                'garage_qual',
                'garage_cond',
                'sale_type']
dummy_columns1

['neighborhood',
 'bldg_type',
 'house_style',
 'heating_qc',
 'central_air',
 'electrical',
 'kitchen_qual',
 'functional',
 'garage_qual',
 'garage_cond',
 'sale_type']

In [12]:
# Create X

# Train X set
X_train = train[features1]

# Test X set
X_test = test[features1]

# Create y_train
y_train = train['saleprice']

In [13]:
# Fill any nulls with 0 
X_train.fillna(0, inplace=True)
X_test.fillna(0, inplace=True)

C:\Users\ncesm\anaconda3\envs\dsi\lib\site-packages\pandas\core\frame.py:4147: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(


In [14]:
# Make dummies / Feature engineering
X_train = pd.get_dummies(data=X_train, columns=dummy_columns1)
X_test = pd.get_dummies(data=X_test, columns=dummy_columns1)

In [17]:
# Set up linear regression
lr1 = LinearRegression()

In [18]:
# fit the model
lr1.fit(X_train, y_train)

LinearRegression()

In [20]:
# now find y_pred or y_test
y_test = lr1.predict(X_test)

In [21]:
y_test[:10]

array([ 92402.75, 142196.5 , 209279.  , 111483.75, 184251.  ,  93858.  ,
       110579.25, 152668.75, 158052.25, 203492.  ])

In [22]:
# now create a column in the test dataframe
test['SalePrice'] = y_test

In [24]:
submissionf1 = test[['id','SalePrice']]
submissionf1.head()

id  SalePrice
0  2658   92402.75
1  2718  142196.50
2  2414  209279.00
3  1989  111483.75
4   625  184251.00

In [42]:
# Rename columns if they are anal about uppercase
submissionf1.rename(columns={'id':'Id'},inplace=True)
submissionf1.columns

C:\Users\ncesm\anaconda3\envs\dsi\lib\site-packages\pandas\core\frame.py:4125: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(


Index(['Id', 'SalePrice'], dtype='object')

In [25]:
# SAVE TO CSV 
submissionf1.to_csv('../submissions/features1.csv', index=False)

# FEATURES 2

In [48]:
features2 = ['ms_subclass',
  'street',
  'alley',
  'neighborhood',
  'bldg_type',
  'house_style',
  'overall_qual',
  'overall_cond',
  'year_built',
  'bsmt_qual',
  'bsmt_cond',
  'heating_qc',
  'central_air',
  'electrical',
  'full_bath',
  'half_bath',
  'bedroom_abvgr',
  'kitchen_qual',
  'totrms_abvgrd',
  'functional',
  'fireplaces',
  'garage_cars',
  'garage_qual',
  'garage_cond',
  'mo_sold',
  'yr_sold',
  'sale_type']

In [49]:
dummy_columns2 = ['street',
                'alley',
                'neighborhood',
                'bldg_type',
                'house_style',
                'bsmt_qual',
                'bsmt_cond',
                'heating_qc',
                'central_air',
                'electrical',
                'kitchen_qual',
                'functional',
                'garage_qual',
                'garage_cond',
                'sale_type']

In [50]:
# Create X

# Train X set
X_train = train[features2]

# Test X set
X_test = test[features2]

# Create y_train
y_train = train['saleprice']

In [51]:
# Fill any nulls with 0
X_train.fillna(0, inplace=True)
X_test.fillna(0, inplace=True)

C:\Users\ncesm\anaconda3\envs\dsi\lib\site-packages\pandas\core\frame.py:4147: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(


In [52]:
# Make dummies
X_train = pd.get_dummies(data=X_train, columns=dummy_columns2)
X_test = pd.get_dummies(data=X_test, columns=dummy_columns2)

In [53]:
# Check which columns are not in the other 
print('These columns dont exist in test dataframe')
for column in X_train.columns:
    if column not in X_test.columns:
        print('-',column)
        
print('SPLIT')
print('These columns dont exist in train dataframe')
for column in X_test.columns:
    if column not in X_train.columns:
        print('-',column)

These columns dont exist in test dataframe
SPLIT
These columns dont exist in train dataframe


In [54]:
# Set up linear regression
lr2 = LinearRegression()

In [55]:
# fit the model
lr2.fit(X_train, y_train)

LinearRegression()

In [56]:
# now find y_pred or y_test
y_test = lr2.predict(X_test)
y_test[:10]

array([101473.5, 149126. , 207967. , 112003.5, 190752. ,  86455.5,
        94749. , 148037.5, 157979.5, 196447. ])

In [57]:
test['SalePrice'] = y_test

In [58]:
submissionf2 = test[['id','SalePrice']]
submissionf2.rename(columns={'id':'Id'},inplace=True)
submissionf2.columns, submissionf2.head()

C:\Users\ncesm\anaconda3\envs\dsi\lib\site-packages\pandas\core\frame.py:4125: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(


(Index(['Id', 'SalePrice'], dtype='object'),
      Id  SalePrice
 0  2658   101473.5
 1  2718   149126.0
 2  2414   207967.0
 3  1989   112003.5
 4   625   190752.0)

In [59]:
# SAVE TO CSV 
submissionf2.to_csv('../submissions/features2.csv', index=False)

# FEATURES 3

In [60]:
features3 = ['ms_subclass',
  'street',
  'alley',
  'neighborhood',
  'bldg_type',
  'house_style',
  'overall_qual',
  'overall_cond',
  'year_built',
  'year_remod/add',
  'bsmt_qual',
  'bsmt_cond',
  'total_bsmt_sf',
  'heating_qc',
  'central_air',
  'electrical',
  '1st_flr_sf',
  'gr_liv_area',
  'full_bath',
  'half_bath',
  'bedroom_abvgr',
  'kitchen_qual',
  'totrms_abvgrd',
  'functional',
  'fireplaces',
  'garage_yr_blt',
  'garage_cars',
  'garage_area',
  'garage_qual',
  'garage_cond',
  'mo_sold',
  'yr_sold',
  'sale_type']

In [61]:
dummy_columns3 = ['street',
                'alley',
                'neighborhood',
                'bldg_type',
                'house_style',
                'bsmt_qual',
                'bsmt_cond',
                'heating_qc',
                'central_air',
                'electrical',
                'kitchen_qual',
                'functional',
                'garage_qual',
                'garage_cond',
                'sale_type']

In [62]:
# Create X

# Train X set
X_train = train[features3]

# Test X set
X_test = test[features3]

# Create y_train
y_train = train['saleprice']

In [63]:
# Fill any nulls with 0
X_train.fillna(0, inplace=True)
X_test.fillna(0, inplace=True)

C:\Users\ncesm\anaconda3\envs\dsi\lib\site-packages\pandas\core\frame.py:4147: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(


In [64]:
# Make dummies
X_train = pd.get_dummies(data=X_train, columns=dummy_columns3)
X_test = pd.get_dummies(data=X_test, columns=dummy_columns3)

In [65]:
# Check which columns are not in the other 
print('These columns dont exist in test dataframe')
for column in X_train.columns:
    if column not in X_test.columns:
        print('-',column)
        
print('SPLIT')
print('These columns dont exist in train dataframe')
for column in X_test.columns:
    if column not in X_train.columns:
        print('-',column)

These columns dont exist in test dataframe
SPLIT
These columns dont exist in train dataframe


In [66]:
# Set up linear regression
lr3 = LinearRegression()

In [67]:
# fit the model
lr3.fit(X_train, y_train)

LinearRegression()

In [68]:
# now find y_pred or y_test
y_test = lr3.predict(X_test)
y_test[:10]

array([130742.74285065, 155240.62906242, 194878.22254024, 111301.48500582,
       181903.69994358,  87650.04606166, 106540.62430881, 159855.81401406,
       186881.39924018, 181144.73514562])

In [69]:
test['SalePrice'] = y_test

In [70]:
submissionf3 = test[['id','SalePrice']]
submissionf3.rename(columns={'id':'Id'},inplace=True)
submissionf3.columns, submissionf3.head()

C:\Users\ncesm\anaconda3\envs\dsi\lib\site-packages\pandas\core\frame.py:4125: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(


(Index(['Id', 'SalePrice'], dtype='object'),
      Id      SalePrice
 0  2658  130742.742851
 1  2718  155240.629062
 2  2414  194878.222540
 3  1989  111301.485006
 4   625  181903.699944)

In [71]:
# SAVE TO CSV 
submissionf3.to_csv('../submissions/features3.csv', index=False)

# Features 1 but treat some features as categorical

In [72]:
features1 = ['ms_subclass',

  'neighborhood',
  'bldg_type',
  'house_style',
  'overall_cond',
  'year_built',

  'heating_qc',
  'central_air',
  'electrical',
  'full_bath',
  'half_bath',
  'bedroom_abvgr',
  'kitchen_qual',
  'totrms_abvgrd',
  'functional',
  'fireplaces',
  'garage_cars',
  'garage_qual',
  'garage_cond',
  'mo_sold',
  'yr_sold',
  'sale_type']

In [73]:
dummy_columns1 = [
                'neighborhood',
                'bldg_type',
                'house_style',
                'overall_cond',
                'heating_qc',
                'central_air',
                'electrical',
                'kitchen_qual',
                'functional',
                'garage_qual',
                'garage_cond',
                'sale_type']

In [74]:
# Create X

# Train X set
X_train = train[features1]

# Test X set
X_test = test[features1]

# Create y_train
y_train = train['saleprice']

In [75]:
# Fill any nulls with 0
X_train.fillna(0, inplace=True)
X_test.fillna(0, inplace=True)

C:\Users\ncesm\anaconda3\envs\dsi\lib\site-packages\pandas\core\frame.py:4147: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(


In [76]:
# Make dummies
X_train = pd.get_dummies(data=X_train, columns=dummy_columns1)
X_test = pd.get_dummies(data=X_test, columns=dummy_columns1)

In [77]:
# Check which columns are not in the other 
print('These columns dont exist in test dataframe')
for column in X_train.columns:
    if column not in X_test.columns:
        print('-',column)
        
print('SPLIT')
print('These columns dont exist in train dataframe')
for column in X_test.columns:
    if column not in X_train.columns:
        print('-',column)

These columns dont exist in test dataframe
SPLIT
These columns dont exist in train dataframe


In [78]:
# Set up linear regression
lr1d = LinearRegression()
# fit it
lr1d.fit(X_train, y_train)

LinearRegression()

In [79]:
# now find y_pred or y_test
y_test = lr1d.predict(X_test)
y_test[:10]

array([106533.75, 138526.  , 209189.5 , 109592.  , 187616.5 ,  93044.  ,
       107607.75, 149888.75, 157876.  , 200703.75])

In [80]:
test['SalePrice'] = y_test


In [81]:
submissionf1d = test[['id','SalePrice']]
submissionf1d.rename(columns={'id':'Id'},inplace=True)
submissionf1d.columns, submissionf1d.head()

C:\Users\ncesm\anaconda3\envs\dsi\lib\site-packages\pandas\core\frame.py:4125: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(


(Index(['Id', 'SalePrice'], dtype='object'),
      Id  SalePrice
 0  2658  106533.75
 1  2718  138526.00
 2  2414  209189.50
 3  1989  109592.00
 4   625  187616.50)

In [83]:
# SAVE TO CSV 
submissionf1d.to_csv('../submissions/features1d.csv', index=False)

# Features 4

These features were ones that had a correlation of .5 or higher in relation to saleprice in the `train` set. This was to set a new benchmark and then rise in numbers from here.

In [84]:
features4 = ['overall_qual',
  'year_built',
  'year_remod/add',
  'mas_vnr_area',
  'total_bsmt_sf',
  '1st_flr_sf',
  'gr_liv_area',
  'full_bath',
  'garage_yr_blt',
  'garage_cars',
  'garage_area']

In [125]:
X_train = train[features4]
X_test = test[features4]
y_train = train['saleprice']

In [126]:
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.select_dtypes.html
dummies_columns = list(clean_train[features4].select_dtypes(include='object'))

In [127]:
# Make dummies
X_train = pd.get_dummies(data=X_train, columns=dummies_columns)
X_test = pd.get_dummies(data=X_test, columns=dummies_columns)

In [128]:
# Fill any nulls with 0
X_train.fillna(0, inplace=True)
X_test.fillna(0, inplace=True)

#### Instantiate and fit to LinearRegression

In [129]:
lr4 = LinearRegression()
lr4.fit(X_train,y_train)

LinearRegression()

In [130]:
# now find y_pred or y_test
y_test = lr4.predict(X_test)
y_test[:10]

array([155633.91075769, 204322.08607043, 191441.68615107, 132685.74768135,
       186404.21807137,  85994.99719214, 111224.7299467 , 141870.8884628 ,
       210439.7166696 , 166247.98950903])

In [131]:
test['SalePrice'] = y_test


In [132]:
submissionf4 = test[['id','SalePrice']]
submissionf4.rename(columns={'id':'Id'},inplace=True)
submissionf4.columns, submissionf4.head()

C:\Users\ncesm\anaconda3\envs\dsi\lib\site-packages\pandas\core\frame.py:4125: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(


(Index(['Id', 'SalePrice'], dtype='object'),
      Id      SalePrice
 0  2658  155633.910758
 1  2718  204322.086070
 2  2414  191441.686151
 3  1989  132685.747681
 4   625  186404.218071)

In [94]:
# SAVE TO CSV 
submissionf4.to_csv('../submissions/features4.csv', index=False)

# SUBMISSION MAKER FEATURES AND LOG

---

# Features1

In [95]:
# Create X

# Train X set
X_train = train[features1]

# Test X set
X_test = test[features1]

# Create y_train
y_train = train['saleprice'].map(np.log)

In [96]:
# Fill any nulls with 0
X_train.fillna(0, inplace=True)
X_test.fillna(0, inplace=True)

C:\Users\ncesm\anaconda3\envs\dsi\lib\site-packages\pandas\core\frame.py:4147: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(


In [97]:
# Make dummies
X_train = pd.get_dummies(data=X_train, columns=dummy_columns1)
X_test = pd.get_dummies(data=X_test, columns=dummy_columns1)

In [98]:
# Check which columns are not in the other 
for column in X_train.columns:
    if column not in X_test.columns:
        print(column)
        
print('SPLIT')
for column in X_test.columns:
    if column not in X_train.columns:
        print(column)

SPLIT


In [99]:
# Set up linear regression
lr1log = LinearRegression()

In [100]:
# fit the model
lr1log.fit(X_train, y_train)

LinearRegression()

In [101]:
# now find y_pred or y_test
y_test = lr1log.predict(X_test)

y_test = np.exp(y_test)

In [102]:
# now create a column in the test dataframe
test['SalePrice'] = y_test

In [103]:
submissionf1 = test[['id','SalePrice']]
submissionf1.head()

id      SalePrice
0  2658   87257.214497
1  2718  140943.635496
2  2414  204568.995423
3  1989  107655.425688
4   625  174287.317168

In [104]:
# Rename columns if they are anal about uppercase
submissionf1.rename(columns={'id':'Id'},inplace=True)
submissionf1.columns

C:\Users\ncesm\anaconda3\envs\dsi\lib\site-packages\pandas\core\frame.py:4125: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(


Index(['Id', 'SalePrice'], dtype='object')

In [105]:
# SAVE TO CSV 
submissionf1.to_csv('../submissions/features1-log.csv', index=False)

# FEATURES 2

In [106]:
# Create X

# Train X set
X_train = train[features2]

# Test X set
X_test = test[features2]

# Create y_train
y_train = train['saleprice'].map(np.log)

In [107]:
# Fill any nulls with 0
X_train.fillna(0, inplace=True)
X_test.fillna(0, inplace=True)

C:\Users\ncesm\anaconda3\envs\dsi\lib\site-packages\pandas\core\frame.py:4147: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(


In [108]:
# Make dummies
X_train = pd.get_dummies(data=X_train, columns=dummy_columns2)
X_test = pd.get_dummies(data=X_test, columns=dummy_columns2)

In [109]:
# Check which columns are not in the other 
print('These columns dont exist in test dataframe')
for column in X_train.columns:
    if column not in X_test.columns:
        print('-',column)
        
print('SPLIT')
print('These columns dont exist in train dataframe')
for column in X_test.columns:
    if column not in X_train.columns:
        print('-',column)

These columns dont exist in test dataframe
SPLIT
These columns dont exist in train dataframe


In [110]:
# Set up linear regression
lr2log = LinearRegression()

In [111]:
# fit the model
lr2log.fit(X_train, y_train)

LinearRegression()

In [112]:
# now find y_pred or y_test
y_test = lr2log.predict(X_test)
y_test = np.exp(y_test)
y_test[:10]

array([ 78380.98984265, 156701.96727459, 208955.78001544, 108322.56903267,
       179866.09862981,  93072.62733937, 102092.46342344, 151479.19727142,
       165135.65266726, 190126.53418477])

In [113]:
test['SalePrice'] = y_test

In [114]:
submissionf2 = test[['id','SalePrice']]
submissionf2.rename(columns={'id':'Id'},inplace=True)
submissionf2.columns, submissionf2.head()

C:\Users\ncesm\anaconda3\envs\dsi\lib\site-packages\pandas\core\frame.py:4125: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(


(Index(['Id', 'SalePrice'], dtype='object'),
      Id      SalePrice
 0  2658   78380.989843
 1  2718  156701.967275
 2  2414  208955.780015
 3  1989  108322.569033
 4   625  179866.098630)

In [115]:
# SAVE TO CSV 
submissionf2.to_csv('../submissions/features2-log.csv', index=False)

# FEATURES 3

In [116]:
# Create X

# Train X set
X_train = train[features3]

# Test X set
X_test = test[features3]

# Create y_train
y_train = train['saleprice'].map(np.log)

In [117]:
# Fill any nulls with 0
X_train.fillna(0, inplace=True)
X_test.fillna(0, inplace=True)

C:\Users\ncesm\anaconda3\envs\dsi\lib\site-packages\pandas\core\frame.py:4147: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(


In [118]:
# Make dummies
X_train = pd.get_dummies(data=X_train, columns=dummy_columns2)
X_test = pd.get_dummies(data=X_test, columns=dummy_columns2)

In [119]:
# Check which columns are not in the other 
print('These columns dont exist in test dataframe')
for column in X_train.columns:
    if column not in X_test.columns:
        print('-',column)
        
print('SPLIT')
print('These columns dont exist in train dataframe')
for column in X_test.columns:
    if column not in X_train.columns:
        print('-',column)

These columns dont exist in test dataframe
SPLIT
These columns dont exist in train dataframe


In [120]:
# Set up linear regression
lr3log = LinearRegression()
# fit the model
lr3log.fit(X_train, y_train)

LinearRegression()

In [121]:
# now find y_pred or y_test
y_test = lr3log.predict(X_test)
y_test = np.exp(y_test)
y_test[:10]

array([ 86709.23774278, 161667.18982817, 196363.64231983, 108925.7127085 ,
       171761.64994569,  94254.21570528, 109483.96513596, 161094.00964808,
       188614.50168482, 177290.70684575])

In [122]:
test['SalePrice'] = y_test

In [123]:
submissionf3 = test[['id','SalePrice']]
submissionf3.rename(columns={'id':'Id'},inplace=True)
submissionf3.columns, submissionf3.head()

C:\Users\ncesm\anaconda3\envs\dsi\lib\site-packages\pandas\core\frame.py:4125: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(


(Index(['Id', 'SalePrice'], dtype='object'),
      Id      SalePrice
 0  2658   86709.237743
 1  2718  161667.189828
 2  2414  196363.642320
 3  1989  108925.712708
 4   625  171761.649946)

In [124]:
# SAVE TO CSV 
submissionf3.to_csv('../submissions/features3-log.csv', index=False)

# Features 4

These features were ones that had a correlation of .5 or higher in relation to saleprice in the `train` set. This was to set a new benchmark and then rise in numbers from here.

In [134]:
# Create X

# Train X set
X_train = train[features4]

# Test X set
X_test = test[features4]

# Create y_train
y_train = train['saleprice'].map(np.log)

In [135]:
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.select_dtypes.html
dummies_columns = list(clean_train[features4].select_dtypes(include='object'))

In [137]:
# Fill any nulls with 0
X_train.fillna(0, inplace=True)
X_test.fillna(0, inplace=True)

In [140]:
# Make dummies
X_train = pd.get_dummies(data=X_train, columns=dummies_columns)
X_test = pd.get_dummies(data=X_test, columns=dummies_columns)

In [141]:
# Check which columns are not in the other 
print('These columns dont exist in test dataframe')
for column in X_train.columns:
    if column not in X_test.columns:
        print('-',column)
        
print('SPLIT')
print('These columns dont exist in train dataframe')
for column in X_test.columns:
    if column not in X_train.columns:
        print('-',column)

These columns dont exist in test dataframe
SPLIT
These columns dont exist in train dataframe


In [142]:
# Set up linear regression
lr4log = LinearRegression()
# fit the model
lr4log.fit(X_train, y_train)

LinearRegression()

In [143]:
# now find y_pred or y_test
y_test = lr4log.predict(X_test)
y_test = np.exp(y_test)
y_test[:10]

array([139372.36782193, 190186.65062654, 191942.67186594, 129657.30400686,
       163605.93201186, 104304.97575991, 119128.26186286, 142756.72583066,
       203658.73084753, 159513.35827129])

In [144]:
test['SalePrice'] = y_test

In [145]:
submissionf4 = test[['id','SalePrice']]
submissionf4.rename(columns={'id':'Id'},inplace=True)
submissionf4.columns, submissionf4.head()

C:\Users\ncesm\anaconda3\envs\dsi\lib\site-packages\pandas\core\frame.py:4125: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(


(Index(['Id', 'SalePrice'], dtype='object'),
      Id      SalePrice
 0  2658  139372.367822
 1  2718  190186.650627
 2  2414  191942.671866
 3  1989  129657.304007
 4   625  163605.932012)

In [146]:
# SAVE TO CSV 
submissionf4.to_csv('../submissions/features4-log.csv', index=False)